services:
  app:
    image: ghcr.io/erbege/bege-crm:latest
    container_name: crm-${CLIENT_CODE}
    restart: unless-stopped
    env_file: .env
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    ports:
      - "127.0.0.1:8080:80"
    networks: [ crm_net ]

  db:
    image: mariadb:10.11
    container_name: db-${CLIENT_CODE}
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes: [ db_data:/var/lib/mysql ]
    networks: [ crm_net ]
    healthcheck:
      test: [ "CMD", "healthcheck.sh", "--connect", "--innodb_initialized" ]
      interval: 10s
      timeout: 5s
      retries: 3

  redis:
    image: redis:7.4-alpine
    container_name: redis-${CLIENT_CODE}
    restart: unless-stopped
    command: >
      redis-server --requirepass ${REDIS_PASSWORD} --appendonly yes --maxmemory 256mb --maxmemory-policy allkeys-lru
    volumes: [ redis_data:/data ]
    networks: [ crm_net ]
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 300M
    healthcheck:
      test: [ "CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 3

  radiusdb:
    image: mariadb:10.11
    container_name: radiusdb-${CLIENT_CODE}
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${RADIUS_DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${RADIUS_DB_DATABASE}
      MYSQL_USER: ${RADIUS_DB_USERNAME}
      MYSQL_PASSWORD: ${RADIUS_DB_PASSWORD}
    volumes:
      - radius_db_data:/var/lib/mysql
      - ./sql/radius-init.sql:/docker-entrypoint-initdb.d/init.sql
    networks: [ crm_net ]
    healthcheck:
      test: [ "CMD", "healthcheck.sh", "--connect", "--innodb_initialized" ]
      interval: 10s
      timeout: 5s
      retries: 3

  radius:
    image: freeradius/freeradius-server:latest
    container_name: radius-${CLIENT_CODE}
    restart: unless-stopped
    depends_on:
      radiusdb:
        condition: service_healthy
    ports:
      - "1812:1812/udp"
      - "1813:1813/udp"
    volumes:
      - ./freeradius:/etc/freeradius
    networks: [ crm_net ]

networks:
  crm_net:

volumes:
  db_data:
  redis_data:
  radius_db_data:
