sqlcounter max_data_volume {
    counter_name = Max-All-Octets
    check_name = Max-All-Octets
    reply_name = Mikrotik-Rate-Limit
    sqlmod-inst = sql
    key = User-Name
    reset = never
    query = "SELECT IFNULL(SUM(acctinputoctets + acctoutputoctets),0) FROM radacct WHERE username = '%{${key}}'"
}
