sqlcounter validity_time {
    counter_name = Max-Validity-Seconds
    check_name = Max-Validity-Seconds
    reply_name = Session-Timeout
    sqlmod-inst = sql
    key = User-Name
    reset = never
    query = "SELECT IFNULL(TIMESTAMPDIFF(SECOND, MIN(acctstarttime), NOW()), 0) FROM radacct WHERE username = '%{${key}}'"
}
